version: 2

models:
  - name: dim_listings_scd_type1
    description: >
      Current state of all listings (Type 1 SCD).
      Use this table for queries that only need the current state
      of listings for better performance and simplicity.

    tests:
      - unique:
          column_name: listing_id
      - not_null:
          column_name: listing_id

    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique:
              name: "unique_listing_id_in_current_dim"
          - not_null:
              name: "not_null_listing_id_in_current_dim"

  - name: dim_listings_scd_type2
    description: "Slowly Changing Dimension Type 2 for listings"
    columns:
      - name: listing_sk
        description: "Surrogate key for the listing dimension"
        tests:
          - unique
          - not_null
      - name: listing_id
        description: "Business key for the listing"
        tests:
          - not_null
      # Original columns...
      - name: host_city
        description: "City extracted from host_location"
      - name: host_country
        description: "Country extracted from host_location"
      - name: host_since
        description: "Date when host joined the platform"
        tests:
          - dbt_utils.not_null_proportion:
              at_least: 0.5

  - name: dim_listings_scd_type3
    description: >
      Type 3 SCD implementation for listings that tracks current, previous, and original values
      for key changing attributes (price, superhost status, room type, minimum nights).
      This model enables time-series analysis of important attribute changes.
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique:
              name: "unique_listing_id_in_type3_dim"
          - not_null:
              name: "not_null_listing_id_in_type3_dim"

      - name: current_price
        description: Current listing price

      - name: previous_price
        description: Previous listing price before the most recent change

      - name: original_price
        description: Original listing price when first added to the system

      - name: price_changed
        description: Boolean flag indicating if price has changed from previous value

      - name: price_percent_change
        description: Percentage change between current and previous price

  - name: fct_reviews
    description: Reviews fact table containing all reviews submitted for listings
    columns:
      - name: review_sk
        description: Surrogate key for the review
        tests:
          - unique
          - not_null
      - name: review_id
        description: Natural key for the review
        tests:
          - unique
          - not_null
      - name: listing_id
        description: Foreign key to dim_listings
        tests:
          - not_null
          - relationships:
              to: ref('dim_listings_scd_type1')
              field: listing_id
      - name: simple_sentiment
        description: Basic sentiment classification based on keyword matching
        tests:
          - accepted_values:
              values: ["positive", "negative", "neutral"]

  - name: dim_reviewers
    description: Reviewer dimension with aggregated metrics
    columns:
      - name: reviewer_id
        description: Primary key for the reviewer
        tests:
          - unique
          - not_null
      - name: total_reviews
        description: Total number of reviews submitted by this reviewer
        tests:
          - not_null

  - name: fct_calendar_daily
    description: >
      Fact table containing daily availability and pricing for all listings.
      This granular fact table enables time-series analysis of listing availability,
      price changes, and booking patterns.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - listing_id
            - calendar_date
    columns:
      - name: listing_id
        description: Foreign key to the dim_listings dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_listings_scd_type1')
              field: listing_id

      - name: calendar_date
        description: The specific date for this calendar entry
        tests:
          - not_null

      - name: is_available
        description: Boolean indicating if the listing is available for booking on this date
        tests:
          - not_null

      - name: price
        description: Listed price for this date in local currency
        tests:
          - dbt_utils.not_null_proportion:
              at_least: 0.9

      - name: adjusted_price
        description: Price after adjustments (seasonal pricing, discounts, etc.)

      - name: minimum_nights
        description: Minimum stay required if booking includes this date
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              inclusive: true

      - name: maximum_nights
        description: Maximum stay allowed if booking includes this date
        tests:
          - not_null

      - name: day_of_week
        description: Numeric day of week (0=Sunday, 6=Saturday)
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]

      - name: month_num
        description: Month number (1-12)
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: year_num
        description: Calendar year
        tests:
          - not_null

      - name: is_weekend
        description: Flag indicating if date is on a weekend
        tests:
          - not_null

      - name: price_change_from_previous_day
        description: Difference in price from the previous calendar day
        tests:
          - not_null

      - name: dbt_loaded_at
        description: Timestamp when this record was loaded by dbt
        tests:
          - not_null

      - name: _ingested_at
        description: Timestamp when this record was ingested from source
        tests:
          - not_null

      - name: record_hash
        description: Hash of key fields for change detection
        tests:
          - not_null
