version: 2

models:
  - name: int_listings_cleaned
    description: Cleaned and standardized listings data
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

  - name: int_reviews_cleaned
    description: Cleaned and validated reviews with sentiment analysis
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: sentiment
        description: Sentiment classification based on review text
        tests:
          - accepted_values:
              values: ["positive", "negative", "neutral"]
      - name: data_quality_check
        description: Data quality assessment for each review
        tests:
          - accepted_values:
              values:
                [
                  "valid",
                  "missing_review_id",
                  "missing_listing_id",
                  "invalid_date_format",
                  "empty_review_text",
                ]

  - name: int_calendar_cleaned
    description: >
      Cleaned and standardized calendar data with availability and pricing information.
      This intermediate model handles data type conversions, format standardization,
      and adds time-based attributes for analysis.
    columns:
      - name: listing_id
        description: Foreign key to the listings table
        tests:
          - not_null
          - relationships:
              to: ref('stg_listings')
              field: listing_id

      - name: calendar_date
        description: The date for which availability is being reported
        tests:
          - not_null

      - name: is_available
        description: Boolean flag indicating if the listing is available on this date
        tests:
          - not_null

      - name: price
        description: >
          The nightly price in local currency (decimal format).
          Cleaned from original string format with currency symbols.
        tests:
          - dbt_utils.not_null_proportion:
              at_least: 0.9

      - name: adjusted_price
        description: >
          The adjusted price after any promotions or dynamic pricing,
          in local currency (decimal format).

      - name: minimum_nights
        description: Minimum number of nights required for booking on this date
        tests:
          - not_null

      - name: maximum_nights
        description: Maximum number of nights allowed for booking on this date
        tests:
          - not_null

      - name: day_of_week
        description: >
          Day of week as integer (0=Sunday, 6=Saturday)
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]

      - name: month_num
        description: Month number (1-12)
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: year_num
        description: Calendar year (e.g., 2023, 2024)
        tests:
          - not_null

      - name: is_weekend
        description: Boolean flag indicating if this date falls on a weekend (Saturday or Sunday)
        tests:
          - not_null

      - name: _ingested_at
        description: Timestamp when this record was ingested from source
        tests:
          - not_null

      - name: record_hash
        description: MD5 hash for change detection
        tests:
          - not_null
