version: 2

models:
  - name: int_listings_cleaned
    description: Cleaned and standardized listings data
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null
