services:
  postgres-test:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_db
    command: ["postgres", "-c", "shared_preload_libraries=pgcrypto"]
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse_user -d warehouse_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio-test:
    image: minio/minio
    container_name: minio-test
    environment:
      MINIO_ROOT_USER: test_access_key
      MINIO_ROOT_PASSWORD: test_secret_key
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test
    depends_on:
      postgres-test:
        condition: service_healthy
      minio-test:
        condition: service_healthy
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - TEST_POSTGRES_HOST=postgres-test
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_USER=warehouse_user
      - TEST_POSTGRES_PASSWORD=warehouse_password
      - TEST_POSTGRES_DB=warehouse_db
      - S3_ENDPOINT=minio-test:9000
      - S3_ACCESS_KEY=test_access_key
      - S3_SECRET_KEY=test_secret_key

  superset:
    init: true
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    volumes:
      - ./superset_home:/app/superset_home
    environment:
      - DATABASE_DB=superset
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
    ports:
      - "8080:8088"

  superset-database:
    init: true
    image: postgres:alpine
    container_name: superset_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=secretsecret
    ports:
      - "5000:5432"

volumes:
  postgres_data:
  minio_data:
