
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: security_key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  superset:
    init: true
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    volumes:
      - ./superset_home:/app/superset_home
    environment:
      - DATABASE_DB=superset
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
    ports:
      - "8080:8088"

  superset-database:
    init: true
    image: postgres:alpine
    container_name: superset_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=secretsecret
    ports:
      - "5000:5432"

volumes:
  postgres_data:
  minio_data: