version: 2

sources:
  - name: bronze
    database: warehouse_db
    schema: bronze
    tables:
      - name: raw_listings
        identifier: raw_listings
        loaded_at_field: _ingested_at
        description: Raw listings data loaded from source files
        columns:
          - name: id
            description: Primary key for the listing
            tests:
              - unique
              - not_null
          - name: host_id
            description: ID of the host
            tests:
              - not_null
          - name: price
            description: Price per night in local currency
            tests:
              - not_null
              - dbt_utils.positive_value

      - name: raw_reviews
        identifier: raw_reviews
        loaded_at_field: _ingested_at
        description: Raw reviews data for listings
        columns:
          - name: id
            description: Primary key for the review
            tests:
              - unique
              - not_null
          - name: listing_id
            description: Foreign key to the listing
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'raw_listings')
                  field: id
          - name: date
            description: Date the review was submitted
            tests:
              - not_null
          - name: reviewer_id
            description: ID of the reviewer
          - name: reviewer_name
            description: Name of the reviewer
          - name: comments
            description: Review text content

      - name: raw_calendar
        description: Daily availability and pricing for listings
        columns:
          - name: listing_id
            description: Foreign key to listings
            tests:
              - not_null
          - name: date
            description: Calendar date
            tests:
              - not_null
models:
  - name: stg_listings
    description: Cleaned and standardized listings data from raw source
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null

      - name: host_id
        description: ID of the host
        tests:
          - not_null

      - name: listing_name
        description: Name/title of the listing
        tests:
          - not_null

      - name: price
        description: Standardized price per night in decimal format
        tests:
          - not_null
          - dbt_utils.positive_value

      - name: data_quality_check
        description: Quality check status for the record
        tests:
          - accepted_values:
              values:
                [
                  "valid",
                  "missing_listing_id",
                  "missing_listing_name",
                  "missing_price",
                  "negative_price",
                  "invalid_accommodates",
                  "negative_minimum_nights",
                  "invalid_maximum_nights",
                ]

      - name: record_hash
        description: MD5 hash for change detection
        tests:
          - not_null

      - name: _dbt_loaded_at
        description: Timestamp when the record was loaded by dbt
        tests:
          - not_null

  - name: stg_reviews
    description: Cleaned and standardized reviews data
    columns:
      - name: review_id
        description: Primary key for the review
        tests:
          - unique
          - not_null
      - name: listing_id
        description: Foreign key to the listing
        tests:
          - not_null
          - relationships:
              to: ref('stg_listings')
              field: listing_id
      - name: review_date
        description: Date the review was submitted
      - name: reviewer_id
        description: ID of the reviewer
      - name: reviewer_name
        description: Name of the reviewer
      - name: review_text
        description: Review text content
      - name: record_hash
        description: MD5 hash for change detection

  - name: stg_calendar
    description: Staged calendar data with availability and pricing
    columns:
      - name: listing_id
        tests:
          - not_null
      - name: calendar_date
        tests:
          - not_null
