version: 2

sources:
  - name: bronze # This is your database schema name
    database: warehouse_db # Replace with your actual database name
    schema: bronze # Using public schema
    tables:
      - name: stg_raw_listings_current
